### ISSUE TITLE
Color labels for events below calendar are a generic color and do not represent their actual color.

### ISSUE THREAD

**Issue by Xalsier** [Xalsier/nak_calendar#1]

**Comment by myCodingcanvas** [comment]
Hi Xalsier, I would like to work on this issue. Can you elaborate??

**Comment by Xalsier** [comment]
> Hi Xalsier, I would like to work on this issue. Can you elaborate??

Yeah, I can elaborate

The two labels were for Chapter Updates 

#71ff4d

And site updates 

#c14dff

Each would color the little circle span

----

I think this issue came about because the span and the label were grouped in divs for each, and I thought removing the groupings would reduce the dom load- but it just messed up the colors

**Comment by Xalsier** [comment]
The grouping looked like this from an earlier commit on the website

`<span class="update-item">
                  <span class="circle site-update"></span> Site Update
                </span>`
                
As far as I've seen though readding that doesnt fix the colors

**Comment by Xalsier** [comment]
Thank you!
